<?php

namespace WarehouseNinja\ShipBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WarehouseNinja\ShipBundle\Entity\OrderProduct;
use WarehouseNinja\ShipBundle\Entity\Product;
use WarehouseNinja\ShipBundle\Entity\Warehouse;

/**
 * OrderProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductRepository extends EntityRepository
{
    /**
     * @param Warehouse $warehouse
     * @param Product $product
     * @return OrderProduct[]
     */
    public function getByWarehouseProduct(Warehouse $warehouse, Product $product)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $queryBuilder->select(array('o'))
            ->from('WarehouseNinjaShipBundle:OrderProduct', 'o')
            ->where('o.warehouse = :warehouse')
            ->setParameter('warehouse',$warehouse)
            ->andWhere('o.product = :product')
            ->setParameter('product', $product);

        return $queryBuilder->getQuery()->getResult();
    }
}
