<?php

namespace WarehouseNinja\ShipBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WarehouseNinja\ShipBundle\Entity\Product;
use WarehouseNinja\ShipBundle\Entity\Stock;
use WarehouseNinja\ShipBundle\Entity\Warehouse;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    /**
     * @param Warehouse $warehouse
     * @param Product $product
     * @return Stock[]
     */
    public function getByWarehouseProduct(Warehouse $warehouse, Product $product)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder();

        $queryBuilder->select(array('s'))
            ->from('WarehouseNinjaShipBundle:Stock', 's')
            ->where('s.warehouse = :warehouse')
            ->setParameter('warehouse',$warehouse)
            ->andWhere('s.product = :product')
            ->setParameter('product', $product);

        return $queryBuilder->getQuery()->getResult();
    }
}
